spring:
  application:
    name: manage-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.128.200.2:3306/useryml?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username: root
    password: 121511
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  jackson:
    time-zone: GMT+8
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 908553683@qq.com #发送邮件的邮箱地址
    password:  ivhkrc*****kbdcf #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1016767658@qq.com # 发送邮件的地址，和上面username一致
  properties.mail.smtp.starttls.enable: true
  properties.mail.smtp.starttls.required: true
  properties.mail.smtp.ssl.enable: true
  default-encoding: utf-8


server:
  port: 8080

store:
  path: C:\data
  temporary: c:\temp



swagger:
  enable: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true