spring:
  application:
    name: manage-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/useryml?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username: root
    password: 121511
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 10000
store:
  path: C:\temp\

swagger:
  enable: true