spring:
  application:
    name: manage-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.128.200.2:3306/useryml?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username: root
    password: 121511
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 121511

server:
  port: 10000

store:
  path: C:\data
  temporary: c:\temp



swagger:
  enable: true